### ISSUE TITLE
[BUG] permission issues on docker update piler 1.4.5 to 1.4.6

### ISSUE THREAD

**Issue by mhoffmann75** [jsuto/piler#112]
**Describe the bug**
When updating dockerized piler 1.4.5 to 1.4.6 manticore seems to have permission issues on it's log file resulting in not starting process and exiting container.

**To Reproduce**
1. Setup dockerized piler 1.4.5
2. Upgrade docker-compose.yml file to use 1.4.6 image
3. See logs of exiting container:

```
piler        | starting searchd . . .
piler        | [Fri Jul 26 10:41:12.597 2024] [65] using config file '/etc/piler/manticore.conf' (3636 chars)...
piler        | [Fri Jul 26 10:41:12.599 2024] [65] FATAL: failed to open log file '/var/piler/manticore/manticore.log': Permission denied
piler        | Manticore 6.3.2 c296dc7c8@24062606 (columnar 2.3.0 88a01c3@24052206) (secondary 2.3.0 88a01c3@24052206) (knn 2.3.0 88a01c3@24052206)
piler        | Copyright (c) 2001-2016, Andrew Aksyonoff
piler        | Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
piler        | Copyright (c) 2017-2024, Manticore Software LTD (https://manticoresearch.com)
piler        | 
piler exited with code 1
```
Mentioned log file `/var/piler/manticore/manticore.log` (see FATAL Error in line 3 of above snippet) has owner piler:piler and 600 (-rw------) permissions.
Even setting logfile permissions to 666 does not make any changes. 

**Expected behavior**
Would be nice to have upgrade from 1.4.5 to 1.4.6 in dockerized environments smooth. 

**Piler version:**
 - 1.4.6

**Comment by th-2021** [comment]
I also run into this. The user piler is now 1001:1001 (was 1000:1000) before. So I had to chown the var-manticore volume.

**Comment by jsuto** [comment]
The solution will be to use the next version's (yet unreleased) docker image. See https://github.com/jsuto/piler/blob/master/docker/docker-compose.yaml. The point is that I use manticore's own docker image, so there shouldn't be more uid or permission issues. Since sutoj/piler:1.4.7 doesn't exist yet, you may use sutoj/piler:test (and perhaps tag it as 1.4.7) to try. The heavy lifting will be migrating data from piler_manticore volume to manticore_data. Or you may simply move the piler_manticore volume definition in the compose.yaml file to manticore container. Anyway, be sure to test the process, before doing it with prod data.

**Comment by Ramalama2** [comment]
I find it almost impossible to upgrade from 1.4.4 to 1.4.6. There are too much changes.
Generally its amazing that there is so much changed and the Project goes on, but some sort of a short upgrade path should be cool.

That permissions 1000 -> 1001 i found out pretty fast either, but there is a lot more.
I have still the no RT version. Additionally the whole public www folder changed, its almost completely incompatible with 1.4.4.
After replacing the whole folder, piler halfway worked, with the new "javascript" GUI that looks identical to the old one xD
However, the search doesnt work, i get no results. Pretty sure that i simply missed some files that i need to exchange, but hell its hard to find out xD

So in the end im still at 1.4.4, probably instead of upgrading, im gonna setup a new instance and migrate+rescan the mails.

**Comment by jsuto** [comment]
@Ramalama2 the no RT stuff is another challenge. For the upcoming release of 1.4.7 I've moved the manticore app to a dedicated image to eliminate the changed uid issue. However, it presents a challenge for RT=0 setups. I'll do my best to make it work. Btw. just curious, do you have a reason to use RT=0?

**Comment by Ramalama2** [comment]
Not really, it's simply just age related. Compared to how long Piler exists (Over 10 Years?), RT is pretty new and i never adopted the changes.

I tryed to adopt it in the beginning, but the changes in the manticore.conf with the kill-list (dailydelta1) changes broke the cron scripts (indexer.delta.sh / indexer.main.sh and as far i remember purge.sh too).
Probably it's fixed since, i didn't tested again since.
But that was the reason i didn't adopted the RT Changes.

To Update to 1.4.6 was my second try recently some days ago :-)

However, it's tbh all not that big of a deal, it just means that i need to spend more time and dig in, or like i said previously create a new instance and migrate the emails over with export and import.
I did the export/import already as i switched from a really old Piler version to v1.4.3 half year ago and it worked pretty good!

TBH, the only thing that i wish, would be some improvements in the "Search" engine.
I mean its working quite well, but sometimes you try to search with wildcards and it finds either nothing or shows a million of emails xD
Pretty sure that it is an issue because Piler is indexing Attachments and some Attachments simply somehow indexes too much (dunno how to explain that better).
An attachment extension whitelist option could be a solution to improve the Search engine.

Anyway, in the end its all not a big of a deal, i have just to dig through. But i believe other people have a hard time either, maybe some aren't even able to Upgrade or migrate, because of lacking knowledge.
The Code itself is quite good tbh, Piler is just lacking a bit in the Documentation department.
Upgrade Paths and a better documentation about the Search engine with more examples etc...
(I would help here out, but im extremely exhausted in the last time, didn't had for over a year a free day from work)

Thanks @jsuto 
Cheers

**Comment by mhoffmann75** [comment]
> I also run into this. The user piler is now 1001:1001 (was 1000:1000) before. So I had to chown the var-manticore volume.

Thank you @th-2021, that did fix my issue.

However I stumbled upon some more issues when upgrading from 1.4.5 to 1.4.6 like:
- needing to manually update manticore.conf (complete `audit1` section missing)
- need of adding `$config['SPHINX_AUDIT_INDEX'] = 'audit1';` to config(-site).php
- changing piler nginx conf php fpm 8.1 to 8.3
- ...

This leads me to the question how can this process made more simple and less error prone?

Either we need some intelligence within the docker entry point files that does all the maintenance (adding config entries, fixing permissions) or at least some Upgrade Documentation file that states what exactly to expect and to do when upgrading from one version to the next one.
What do you think?

**Comment by jsuto** [comment]
1.4.5 uses ubuntu:22.04, however 1.4.6 has ubuntu:24.04. The latter introduced a new user ubuntu with id 1000, that caused some issues you mentioned above. Hopefully they won't occur again until ubuntu:26.04.

However, I wonder how the audit1 index is not present in 1.4.6 image? /var/piler/www is not on a volume, so it should be there.

**Comment by jsuto** [comment]
@Ramalama2 you are correct, the docs could be improved. How about if I open the repo containing the www.mailpiler.org site?

**Comment by Ramalama2** [comment]
> @Ramalama2 you are correct, the docs could be improved. How about if I open the repo containing the [www.mailpiler.org](http://www.mailpiler.org) site?

Thats actually a clever move, just not sure if its worth it. I mean with "worth it", if people contribute/help out with the docs 🙈

**Comment by jsuto** [comment]
OK, this is the repo: https://github.com/jsuto/mailpilerorg-site. Let's see if people want to contribute to the docs :-)
