### ISSUE TITLE
[BUG] If `pilerimport -r ` does not import a message, it should not delete it

### ISSUE THREAD

**Issue by dilyanpalauzov** [jsuto/piler#148]
`pilerimport -r` does delete imported messages.  However if two messages have no Message-ID header, the only one of the message is imported, a duplicate message is printed, but both messages are deleted.  Under these circumstances, `pilerimport -r` should keep the not-imported messages.

Another case, where emails should possibliy not be deleted by `pilerimport -r` are those logging `error: helper: execl`.

**Comment by jsuto** [comment]
To me a message without a proper Message-ID is a bogus one. They really should have based on the RFCs. Anyway, try setting ```archive_emails_not_having_message_id=1``` in piler.conf to import them.

The errors or warning from the external extractor utilities doesn't mean the message is not archived. And since they are in fact archived, pilerimport removes those messages.

**Comment by dilyanpalauzov** [comment]
> To me a message without a proper Message-ID is a bogus one. 

These messages are exported from an older version of Piler (I think 1.1.1).

**Comment by jsuto** [comment]
It's not piler version related. Even 1.1.1 preserves and returns the message as it is.

**Comment by dilyanpalauzov** [comment]
Then I do not understand.  I do `pilerexport` in old version, then `pilerimport` in the new version.  The output contains:

> duplicate: ./6608154.eml (duplicate id: 4789233)

My understanding is, that because that message has no Message-ID, the duplicate-waring is emitted.
