### ISSUE TITLE
Allow to rename admin@local to another user

### ISSUE THREAD

**Issue by vmario89** [jsuto/piler#90]
Hi,
when having piler frontend available to public it would be helpful to be able to rename the admin@local user. This is a weakness in security, even if we have strong password and 2FA enabled. First step to prevent hacking tries from outside, is to rename the default user names, chaning default urls, default ports and so on

i tried to mess with SQL  but the system ignores the changes admin user name, even after restarting all services and browser cache:

```
MariaDB [piler]> UPDATE user SET username='thenewsecure-admin' WHERE username='admin' and domain='local';
MariaDB [piler]> UPDATE user_settings SET username='thenewsecure-admin@local' WHERE username='admin@local';
```

**Comment by jsuto** [comment]
I'm not sure if changing the username actually adds any meaningful security to the system. I think it's more like security by obscurity. Like everyone knows that all Unix systems has a root user, still nobody wants to rename it.

Anyway, you can rename the default builtin user account, the sql statements look appropriate, though you should fix the email table as well. What happens when you login using the new admin account? Does the GUI recognize that you are an admin?

Another option could be to login as admin@local, create another user with admin role, then delete the admin@local account.

**Comment by vmario89** [comment]
the root user of linux is usually not able to be SSH'd for example, but the piler user is not secured that way (only if we hide by intranet/VPN solution). Its a difference in exposure

thanks for the hint with email. that works!


```
mysql -uroot
use piler;

UPDATE user SET username='thenewsecure-admin' WHERE username='admin' and domain='local';
UPDATE user_settings SET username='thenewsecure-admin@local' WHERE username='admin@local';
UPDATE email SET email='thenewsecure-admin@local' WHERE email='admin@local';

UPDATE user SET username='thenewsecure-auditor' WHERE username='auditor' and domain='local';
UPDATE user_settings SET username='thenewsecure-auditor@local' WHERE username='auditor@local';
UPDATE email SET email='thenewsecure-auditor@local' WHERE email='auditor@local';
```

```
